package dk.bkskjold.nemsport.Models

import android.os.Parcel
import android.os.Parcelable
import com.google.firebase.Timestamp
import java.util.*
import kotlin.collections.ArrayList


//this class is used to store the data from the firebase database
//this class is parcelable so it can be passed between activities
//the parcelable object is auto generated by the android studio
data class EventModel(
        var eventName: String? = "",
        var eventTime:Timestamp = Timestamp(Calendar.getInstance().getTime()),
        var eventDescription:String = "",
        var pitches:String = "",
        val eventCreaterUID:String = "",
        val participants:ArrayList<String> = ArrayList(),
        val id: String = ""
)  : Parcelable {
    constructor(parcel: Parcel) : this(
        parcel.readString(),
        parcel.readParcelable(Timestamp::class.java.classLoader)!!,
        parcel.readString()!!,
        parcel.readString()!!,
        parcel.readString()!!,
        parcel.readArrayList(null) as ArrayList<String>
        ,parcel.readString()!!
    ) {
    }
    
    override fun writeToParcel(parcel: Parcel, flags: Int) {
        parcel.writeString(eventName)
        parcel.writeParcelable(eventTime, flags)
        parcel.writeString(eventDescription)
        parcel.writeString(pitches)
        parcel.writeString(eventCreaterUID)
        parcel.writeList(participants)
        parcel.writeString(id)
    }

    override fun describeContents(): Int {
        return 0
    }

    companion object CREATOR : Parcelable.Creator<EventModel> {
        override fun createFromParcel(parcel: Parcel): EventModel {
            return EventModel(parcel)
        }

        override fun newArray(size: Int): Array<EventModel?> {
            return arrayOfNulls(size)
        }
    }
}
